# Generated by Django 6.0.6 on 2026-06-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_watchlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["symbol"]},
        ),
    ]
